spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: dnfwlq1
    password: ybqjnzduvnsmpwfl
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true